# Generated by Django 5.1.3 on 2024-12-05 22:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("secretaria", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="reparacion",
            name="estado",
            field=models.BooleanField(default=False),
        ),
        migrations.RemoveField(
            model_name="ordentrabajo",
            name="reparacion",
        ),
        migrations.AddField(
            model_name="ordentrabajo",
            name="reparacion",
            field=models.ManyToManyField(to="secretaria.reparacion"),
        ),
    ]
